name: add-label-triage.yaml

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  automate-issues-labels:
    name: Add triage label to issue
    runs-on: ubuntu-latest
    steps:
      - name: Add triage label
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "triage"
